apiVersion: 1

datasources:
  - name: Acoupi Postgres
    uid: acoupi-postgres
    type: postgres
    access: proxy
    url: ${GRAFANA_DATABASE_HOST}
    user: ${GRAFANA_DATABASE_USER}
    secureJsonData:
      password: ${GRAFANA_DATABASE_PASSWORD}
    jsonData:
      database: ${GRAFANA_DATABASE_NAME}
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
